### ISSUE TITLE
What is "title" error?

### ISSUE THREAD

**Issue by Marxsal** [tiddly-gittly/tw5-plugin-packer#3]
When I try using this, I get null error. It seems to be having problems reading a "title" ?? But I don't know if it means the source title (which is fine) or the output title or some other unspecified title.

Thank you!

```
Run tiddly-gittly/tw5-plugin-packer@v0.0.5
  with:
    source: "plugins/bimlas/kin-filter"
  
    output: ./pluginsJSON
    minify: true
Error: Cannot read properties of null (reading 'title')
```

**Comment by linonetwo** [comment]
Does this mean the tiddler title? Are you adding a new plugin to the CPL?

**Comment by Gk0Wk** [comment]
Can I have a look at your repo?

**Comment by Marxsal** [comment]
I don't know what CPL is. 

This is the repository:

https://github.com/Marxsal/tw-personal-plugin-library

Thanks!

**Comment by Gk0Wk** [comment]
@Marxsal There are two issues that need attention.

1. Before using this action, please use `actions/checkout@v2` to make sure the repo can visit files properly.
2. Each line in `source` cannot be wrapped in quotes.

The new workflow will probably look like this:

```yaml
name: Build JSON Plugins

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: tiddly-gittly/tw5-plugin-packer@v0.0.6
        with:
          source: |
            plugins/bimlas/kin-filter
          output: pluginsJSON
```

---

BTW, CPL is a new platform for sharing and distributing TW plugins, which can be likened to "TW's app store". It can help developers to publish their plugins more easily and increase their influence. For more information, please see: https://talk.tiddlywiki.org/t/tiddlywiki-cpl-tiddlywiki-world-of-google-app-store/2140/8
