### ISSUE TITLE
Where does the output go?

### ISSUE THREAD

**Issue by Marxsal** [tiddly-gittly/tw5-plugin-packer#4]
I can run the process without error, but nothing is generated. Perhaps I am misunderstanding. I thought it would create a directory with the name of the output parameter and fill it with generated JSON files. But this does not happen.

https://github.com/Marxsal/tw-personal-plugin-library

```
# This is a basic workflow to help you get started with Actions

name: Build JSON Plugins

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: tiddly-gittly/tw5-plugin-packer@v0.0.5
        with:
          source: |
            plugins/bimlas/kin-filter
          output: plugins-JSON
```
